package com.example.warehouse;

import javax.annotation.PostConstruct;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.Transactional;

import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class LoadDatabase implements CommandLineRunner {

    @PersistenceContext
    private EntityManager entityManager;

    @Override
    @Transactional
    public void run(String... args) throws Exception {
        resetDatabase();
    }

    @Transactional
    public void resetDatabase() {
        dropTables();
        createTables();
    }

    private void dropTables() {
        entityManager.createNativeQuery("DROP TABLE IF EXISTS outbound_order CASCADE").executeUpdate();
        entityManager.createNativeQuery("DROP TABLE IF EXISTS sku CASCADE").executeUpdate();
    }

    private void createTables() {
        entityManager.createNativeQuery(
                "CREATE TABLE outbound_order (" +
                        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "order_number VARCHAR(255), " +
                        "sku VARCHAR(255), " +
                        "quantity INTEGER)"
        ).executeUpdate();

        entityManager.createNativeQuery(
                "CREATE TABLE sku (" +
                        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "sku VARCHAR(255), " +
                        "name VARCHAR(255), " +
                        "description VARCHAR(255), " +
                        "quantity INTEGER NOT NULL)"
        ).executeUpdate();
    }
}
